const TREE_TYPES = {
    MIRROR: 'MIRROR',
    HEAT: 'HEAT'
};

const MIRROR_TYPES = {
    PURPLE: 'PURPLE',
    GREEN: 'GREEN'
};

const INTERPOLATION_TYPES = {
    META_UPGRADE_PROPERTY: 'META_UPGRADE_PROPERTY'
};

const INTERPOLATION_PROPERTY_TYPES = {
    BASE: 'BASE',
    DELTA: 'DELTA',
    DISPLAY: 'DISPLAY',
    TOTAL: 'TOTAL'
};

const ALL_META_UPGRADE_TYPES = {
    TREE_TYPES,
    MIRROR_TYPES,
    INTERPOLATION_TYPES,
    INTERPOLATION_PROPERTY_TYPES
};

export { ALL_META_UPGRADE_TYPES };
