const ENDIANNESS = {
    BIG: 'BIG_ENDIAN',
    LITTLE: 'LITTLE_ENDIAN'
};

const DEFAULT_ENDIANNESS = ENDIANNESS.BIG;

const ENCODING = {
    UTF8: 'ENCODING_UTF8',
    UTF16: 'ENCODING_UTF16'
};

const DEFAULT_ENCODING = ENCODING.UTF8;

export { ENDIANNESS, DEFAULT_ENDIANNESS, ENCODING, DEFAULT_ENCODING };
