const INTEGER_PRIMITIVE_TYPES = {
    INT8: 'INT8',
    INT16: 'INT16',
    INT32: 'INT32',
    INT64: 'INT64',

    UINT8: 'UINT8',
    UINT16: 'UINT16',
    UINT32: 'UINT32',
    UINT64: 'UINT64'
};

const FLOATING_POINT_PRIMITIVE_TYPES = {
    FLOAT32: 'FLOAT32',
    FLOAT64: 'FLOAT64'
};

const BOOLEAN_PRIMITIVE_TYPES = {
    BOOL8: 'BOOL8'
};

const STRING_PRIMITIVE_TYPES = {
    STRING_NT: 'STRING_NT',
    STRING_NN: 'STRING_NN'
};

const PRIMITIVE_TYPES = {
    ...INTEGER_PRIMITIVE_TYPES,
    ...FLOATING_POINT_PRIMITIVE_TYPES,
    ...BOOLEAN_PRIMITIVE_TYPES,
    ...STRING_PRIMITIVE_TYPES
};

export { PRIMITIVE_TYPES };
