const FILE_SIGNATURE = 826427219;

const SAVE_CHECKSUM_OFFSET = 8;

const SUPPORTED_SAVE_VERSIONS = [16];

const LUA_STATE_DECOMPRESSED_BYTE_SIZE_BY_SAVE_VERSION = {
    16: 9388032
};

export {
    FILE_SIGNATURE,
    SAVE_CHECKSUM_OFFSET,
    SUPPORTED_SAVE_VERSIONS,
    LUA_STATE_DECOMPRESSED_BYTE_SIZE_BY_SAVE_VERSION
};
